---
title: "Exploratory Analysis"
output: html_document
date: "2024-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here we just load some packages that may be useful

```{r}

library(tidyverse)
library(ggplot2)
```

```{r}
# A function that can scan through my csv collection
find_files_direcory = function(directory, ending){
  x = c()
  for(i in list.files(directory, pattern = ending)){
    z = paste(directory, "/", sep = "")
    x = append(x, paste(z,i, sep = ""))
  }
  return(x)
}
find_files = function(ending){
  x = c()
  for(i in list.files()){
    y = list.files(path = i, pattern = ending)
    for(j in y){
      z = paste(i, "/", sep = "")
      x = append(x, paste(z,j, sep = ""))
    }
  }
  return(x)
}
#A function that outputs the average of each column
row_average = function(input_df, st, ed){
  size = dim(input_df)[1]
  adds = colSums(input_df[st:ed])
  return(adds/size)
}

#A function that subtracts each row by a given value in the row
row_diff = function(input_df, tar, st, ed){
  return(input_df[st:ed] - input_df[tar])
}

remove_zeros = function(input_df){
  df[!rowSums(df[-c(1:2)] == 0) >= 1,]
}
simple_line_plot = function(input_df, title){
  size = dim(input_df)[2]
  input_df[2:size][input_df[2:size] == 0] = NA
  ggplot(input_df, aes(x=GC, y=Q_score, group = run, colour = run)) +
  geom_line(size = 1) + 
  expand_limits(x = c(0,1), y = c(0,50)) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        text=element_text(size=15),
        legend.position=c(.9,.9),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  ggtitle(title)
}
#subset(GC_Q_Grid_Ecoli, Q_score != 0)
#simple_line_plot(GC_Q_Grid_Ecoli, "GC Plot for Ecoli Minion")

combine_gc_q = function(lis, names){
  count = 1
  for(i in lis){
    if(count == 1){
      x = i[1]
    }
    x[names[count]] = i[2]
    count = count + 1
  }
  return(x)
}

combine_gc_q_ggplot = function(lis,names){
  count = 1
  for(i in lis){
    if(count == 1){
      x = i
      x['run'] = names[count]
      count = count + 1
    }
    else if(count != 1){
      y = i
      y['run'] = names[count]
      x = rbind(x,y)
      count = count + 1
    }
  }
  return(x)
}

name_from_files = function(location, pattern){
  x = c()
  files = list.files(location,pattern)
  for(i in files){
    s = unlist(strsplit(i, split="_", fixed = T))[1]
    x = append(x, s)
  }
  return(x)
}

create_gc_q_plots = function(directory, title){
  files = lapply(find_files_direcory(directory, "GC_Q.csv"), read.csv)
  df = combine_gc_q_ggplot(files, name_from_files(directory,"GC_Q.csv"))
  simple_line_plot(df, title)
  name = paste(title, ".png", sep = "")
  ggsave(name, width= 10, height = 10)
}
#name_from_files("MinION_Ecoli","GC_Q.csv")

avg_q_summary = function(){
  files = lapply(find_files("Avg_Q"), read.csv)
  names = c()
  for(i in find_files("Avg_Q")){
    temp = unlist(strsplit(i, split = "/", fixed = T))[2]
    temp1 = unlist(strsplit(temp, split = "_", fixed = T))[3]
    temp2 = unlist(strsplit(temp, split = "_", fixed = T))[4]
    temp2 = unlist(strsplit(temp2, split = ".", fixed = T))[1]
    temp = paste(temp1, temp2, sep = "_")
    names = append(names, temp)
  }
  count = 1
  for(i in files){
    temp2 = c()
    temp = NA
    for(j in 3:7){
      p = t.test((i[,j] - i[,2]), mu = 0, alternative = "two.sided")
      p = p["p.value"][[1]]
      temp2 = append(temp2, p)
    }
    if(count == 1){
      y = as.data.frame(temp2)
      y = t(y)
      print(y)
      colnames(y) = colnames(i[3:7])
    }
    else{
      temp2 = as.data.frame(temp2)
      temp2 = t(temp2)
      colnames(temp2) = colnames(i[3:7])
      y = rbind(y, temp2)
    }
    if(count == 1){
      temp = row_average(i,2,7)
      temp = row_diff(temp,1,2,6)
      x = as.data.frame(temp)
    }
    else {
      temp = row_average(i,2,7)
      temp = row_diff(temp,1,2,6)
      x = cbind(x,as.data.frame(temp))
    }
    count = count + 1
  }
  colnames(x) = names
  x = t(x)
  rownames(y) = rownames(x)
  return(list(x,y))
}

average_error_rate_summary = function(directory){
  files = lapply(find_files_direcory(directory, "errors"), read.csv)
  name = directory
  count = 1
  for(i in files){
    if(count == 1){
      x = i
    }
    else{
      x[2:5] = x[2:5] + i[2:5]
    }
    count = count + 1
  }
  x[2:5] = x[2:5] / count
  x['total'] = rowSums(x[2:5])
  return(x)
}

average_error_rate_summary_multiple = function(directs){
  temp = list()
  count = 1
  for(i in directs){
    print(i)
    temp[[count]] = average_error_rate_summary(i)
    count = count + 1
  }
  return(temp)
}

average_error_rate_graph = function(arr, selection = 1, title, names){
  
  count = 1
  new_names = c()
  for(i in names){
    new_names = append(new_names, unlist(strsplit(i, "_"))[1])
  }
  for(i in arr){
    if(count == 1){
      x = i[selection, 2:6]
      x = t(x)
      x = as.data.frame(x)
      x['Error Type'] = rownames(x)
      x['Sequencer'] = new_names[count]
    }
    else{
      temp = i[selection, 2:6]
      temp = t(temp)
      temp = as.data.frame(temp)
      temp['Error Type'] = rownames(temp)
      temp['Sequencer'] = new_names[count]
      x = rbind(x, temp)
    }
    count = count + 1
  }
  colnames(x) = c("Error Rate", "Error Type", "Sequencer")
  #return(x)
  ggplot(x, aes(x = Sequencer, y = `Error Rate`, fill = `Error Type`)) +
    geom_bar(stat = "identity", position = position_dodge(), color = 'black') +
    theme_bw() +
    expand_limits(y = c(0,0.1)) +
    ggtitle(title) + 
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.9,.85),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"))
  
  filename = paste(title, ".png", sep = "")
  ggsave(filename, width = 10, height = 10)
}

average_error_rate_graph_poly = function(arr, selection = 1, title, names){
  
  count = 1
  new_names = c()
  for(i in names){
    new_names = append(new_names, unlist(strsplit(i, "_"))[1])
  }
  for(i in arr){
    if(count == 1){
      i[selection, 4] = i[(selection+1),4]
      if(selection != 1){i[selection, 6] = i[selection, 6] + i[(selection+1),4]}
      x = i[selection, 2:6]
      x = t(x)
      x = as.data.frame(x)
      x['Error Type'] = rownames(x)
      x['Sequencer'] = new_names[count]
    }
    else{
      i[selection, 4] = i[(selection+1),4]
      if(selection != 1){i[selection, 6] = i[selection, 6] + i[(selection+1),4]}
      temp = i[selection, 2:6]
      temp = t(temp)
      temp = as.data.frame(temp)
      temp['Error Type'] = rownames(temp)
      temp['Sequencer'] = new_names[count]
      x = rbind(x, temp)
    }
    count = count + 1
  }
  colnames(x) = c("Error Rate", "Error Type", "Sequencer")
  #return(x)
  ggplot(x, aes(x = Sequencer, y = `Error Rate`, fill = `Error Type`)) +
    geom_bar(stat = "identity", position = position_dodge(), color = 'black') +
    theme_bw() +
    expand_limits(y = c(0,0.1)) +
    ggtitle(title) + 
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.9,.85),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"))
  
  filename = paste(title, ".png", sep = "")
  ggsave(filename, width = 10, height = 10)
}

average_error_rate_comparisons = function(arr,title,names){
  count = 1
  new_names = c()
  for(i in names){
    new_names = append(new_names, unlist(strsplit(i, "_"))[1])
  }
  for(i in arr){
    if(count == 1){
      i[2,6] = i[2,6] + i[3,4]
      i[4,6] = i[4,6] + i[5,4]
      i[6,6] = i[6,6] + i[7,4]
      i[8,6] = i[8,6] + i[9,4]
      i[10,6] = i[10,6] + i[11,4]
      x = c(i[1,6], i[2,6], i[4,6], i[6,6], i[8,6], i[10,6])
      x = as.data.frame(x)
      colnames(x) = "Error Rate"
      x['Sequencer'] = new_names[count]
      x['Condition'] = c("Flat Error Rate", "All Polymers", "AT Polymers",
                         "GC Polymers", "Tri-nucleotide Repeats",
                         "Di-nucleotide Repeats")
    }
    else{
      i[2,6] = i[2,6] + i[3,4]
      i[4,6] = i[4,6] + i[5,4]
      i[6,6] = i[6,6] + i[7,4]
      i[8,6] = i[8,6] + i[9,4]
      i[10,6] = i[10,6] + i[11,4]
      temp = c(i[1,6], i[2,6], i[4,6], i[6,6], i[8,6], i[10,6])
      temp = as.data.frame(temp)
      colnames(temp) = "Error Rate"
      temp['Sequencer'] = new_names[count]
      temp['Condition'] = c("Flat Error Rate", "All Polymers", "AT Polymers",
                         "GC Polymers", "Tri-nucleotide Repeats",
                         "Di-nucleotide Repeats")
      x = rbind(x, temp)
    }
    count = count + 1
  }
  ggplot(x, aes(x = Sequencer, y = `Error Rate`, fill = Condition)) +
    geom_bar(stat = "identity", position = position_dodge(), color = 'black') +
    theme_bw() +
    expand_limits(y = c(0,0.15)) +
    ggtitle(title) + 
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.85,.85),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black"))
  
  filename = paste(title, ".png", sep = "")
  ggsave(filename, width = 10, height = 10)
}

at_vs_gc = function(arr, names, title){
  
  count = 1
  new_names = c()
  for(i in names){
    new_names = append(new_names, unlist(strsplit(i, "_"))[1])
  }
  for(i in arr){
    if(count == 1){
      i[4,6] = i[4,6] + i[5,4]
      i[6,6] = i[6,6] + i[7,4]
      x = i[c(2,6),]
      x['Sequencer'] = new_names[count]
      x['Polymer Type'] = 'AT'
      x = x[6:8]
      x = x[1:2,]
      x[2,3] = 'GC'
    }
    else{
      i[4,6] = i[4,6] + i[5,4]
      i[6,6] = i[6,6] + i[7,4]
      temp = i[c(2,6),]
      temp['Sequencer'] = new_names[count]
      temp['Polymer Type'] = 'AT'
      temp = temp[6:8]
      temp = temp[1:2,]
      temp[2,3] = 'GC'
      x = rbind(x, temp)
    }
    count = count + 1
  }
  ggplot(x, aes(x = Sequencer, y = total, fill = `Polymer Type`)) +
    geom_bar(stat = "identity", position = position_dodge(), color = 'black') +
    theme_bw() +
    expand_limits(y = c(0,0.1)) +
    ggtitle(title) + 
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.9,.85),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) +
    ylab("Total Error Rate") +
    scale_fill_manual(values = c('brown2','cyan3'))
  
  filename = paste(title, ".png", sep = "")
  ggsave(filename, width = 10, height = 10)
  
}

analysis_prep = function(directory, pattern = "GC.csv"){
  files = lapply(find_files_direcory(directory, pattern), read.csv)
  names = c()
  for(i in find_files_direcory(directory,pattern)){
    s = unlist(strsplit(i, split="/", fixed = T))[2]
    s = unlist(strsplit(s, split="_", fixed = T))[1]
    names = append(names, s)
  }
  count = 1
  for(i in files){
    if(count == 1){
      x = i
      x['Total'] = rowSums(x[2:5])
      x['Run'] = names[count]
    }
    else{
      temp = i
      temp['Total'] = rowSums(temp[2:5])
      temp['Run'] = names[count]
      x = rbind(x, temp)
    }
    count = count + 1
  }
  size = dim(x)[2]
  x[2:size][x[2:size] == 0] = NA
  return(x)
}

indel_sizes_plots = function(limit = 25){
  files = lapply(find_files("Sizes.csv"), read.csv)
  names = c()
  for(i in find_files("Sizes.csv")){
    s = unlist(strsplit(i, split = "/", fixed = T))[2]
    s = unlist(strsplit(s, split = ".", fixed = T))[1]
    s = gsub("_", " ", s)
    names = append(names, s)
  }
  count = 1
  for(i in files){
    
    ggplot(data = i[1:limit,], aes(x=Size, y = Count)) +
      geom_bar(stat = "identity", colour = 'darkblue', fill = "steelblue") +
      theme_bw() +
      theme(plot.title = element_text(hjust = 0.5),
            text=element_text(size=15),
            legend.position=c(.9,.75),
            legend.background = element_blank(),
            legend.box.background = element_rect(colour = "black")) +
      ggtitle(names[count]) +
      ylab("Counts") +
      xlab(paste(unlist(strsplit(names[count], split = " "))[3], "Sizes", sep = " ")) +
      scale_x_continuous(breaks = seq(0, 25, 1))
    
    filename = paste(names[count], ".png", sep = "")
    ggsave(filename, width = 10, height = 10)
    count = count + 1
  }
}

create_gc_total_plots = function(df, title){
  
  ggplot(df, aes(x=GC_content, y=Total, group = Run, colour = Run)) +
    geom_line(size = 1) + 
    expand_limits(x = c(0,1), y = c(0,0.2)) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.9,.75),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) +
    ggtitle(title) +
    xlab("GC Content") +
    ylab("Error Rate")
  
  name = paste(title, ".png", sep = "")
  ggsave(name, width= 10, height = 10)
}

create_region_total_plots = function(df, title){
  
  ggplot(df, aes(x=block, y=Total, group = Run, colour = Run)) +
    geom_line(size = 1) + 
    expand_limits(x = c(0,1), y = c(0,0.2)) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.9,.75),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) +
    ggtitle(title) +
    xlab("Read Region") +
    ylab("Error Rate")
  
  name = paste(title, ".png", sep = "")
  ggsave(name, width= 10, height = 10)
}

create_polymer_total_plots = function(df, title){
  
  ggplot(df, aes(x=homopolymer_size, y=Total, group = Run, colour = Run)) +
    geom_point(size = 2) + 
    geom_line(size = 1) +
    expand_limits(x = c(0,1), y = c(0,0.2)) +
    theme_bw() +
    theme(plot.title = element_text(hjust = 0.5),
          text=element_text(size=15),
          legend.position=c(.1,.85),
          legend.background = element_blank(),
          legend.box.background = element_rect(colour = "black")) +
    ggtitle(title) +
    xlab("Homopolymer Size") +
    ylab("Error Rate") +
    scale_x_continuous(breaks = seq(0, 12, 1))
  
  name = paste(title, ".png", sep = "")
  ggsave(name, width= 10, height = 10)
}

```

```{r}
directories = c("MinION_Ecoli", "GridION_Ecoli", "PromethION_Ecoli", "HiSeq2000_Ecoli",
                "PacBIO_Ecoli", "IonTorrent_Ecoli", "MinION_Human",  "GridION_Human",
                "PromethION_Human", "HiSeq2000_Human", "PacBIO_Human", "IonTorrent_Human",
                "NextSeq2000_Ecoli", "NovaSeq6000_Ecoli", "NovaSeq6000_Human")
directories_ecoli = c("MinION_Ecoli", "GridION_Ecoli", "PromethION_Ecoli", 
                      "HiSeq2000_Ecoli", "PacBIO_Ecoli", "IonTorrent_Ecoli",
                      "NextSeq2000_Ecoli", "NovaSeq6000_Ecoli")
directories_human = c("MinION_Human",  "GridION_Human","PromethION_Human", 
                      "HiSeq2000_Human", "PacBIO_Human", "IonTorrent_Human",
                      "NovaSeq6000_Human")
directories_second = c("HiSeq2000_Ecoli2", "HiSeq2000_Human2", "IonTorrent_Ecoli2",
                       "MinION_Human2", "PacBIO_Ecoli2","PromethION_Ecoli2")
directories_ecoli_illumina = c("HiSeq2000_Ecoli","NextSeq2000_Ecoli","NovaSeq6000_Ecoli")
```



Producing plots for Q-score GC

```{r}
for(i in directories){
  name = gsub("_", " ", i)
  name = paste("Average Q-score for", name)
  name = paste(name, "runs")
  create_gc_q_plots(i, name)
}
```
```{r}
for(i in directories){
  name = gsub("_", " ", i)
  name = paste("Total Error Rate for", name)
  name = paste(name, "Runs Against GC Content")
  create_gc_total_plots(analysis_prep(i), name)
}
```

```{r}
for(i in directories){
  name = gsub("_", " ", i)
  name = paste("Region Total Error Rate for", name)
  name = paste(name, "Runs")
  create_region_total_plots(analysis_prep(i, "regions"), name)
}
```

```{r}
for(i in directories){
  name = gsub("_", " ", i)
  name = paste("Total Error Rate for", name)
  name = paste(name, "Runs Against Homopolymer Size")
  create_polymer_total_plots(analysis_prep(i, "hompolymers"), name)
}
```

## Including Plots

You can also embed plots, for example:

```{r, echo=FALSE}
ggplot(test, aes(x = Sequencer, y = `Error Rate`, fill = `Error Type`)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_bw() +
  theme(legend.position=c(.9,.75),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"),
        text=element_text(size=15))
  
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



### Here we're looking at the different encoding methods


```{r}
# Substitution rates

sub_perc = seq(0.00,0.1,length = 21)
DNA_Aeon = c(NA,NA,NA,NA,NA,NA,NA,1,0.1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Hedges = c(NA,NA,NA,NA,NA,NA,NA,1,0.9,0.1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Grass = c(NA,NA,1,0.9,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Derrick = c(NA,1, 0.4, 0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Wukong = c(1,0.8,0.7,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)

sub_errors = data.frame(sub_perc, DNA_Aeon, Hedges, Derrick, Grass, Wukong)

#Insertion Rates
DNA_Aeon = c(NA,NA,NA,1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Hedges = c(NA,NA,NA,NA,NA,NA,1,0.3,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Derrick = c(NA,NA,1,0.1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Grass = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Wukong = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
`Grass + Wukong` = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
ins_errors = data.frame(sub_perc, DNA_Aeon, Hedges, Derrick, Grass, Wukong, `Grass + Wukong`)

#Deletions Rates
DNA_Aeon = c(NA,NA,1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Hedges = c(NA,NA,NA,NA,NA,NA,NA,1,0.4,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Derrick = c(NA,NA,1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
`DNA-Aeon + Derrick` = c(NA,NA,1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Grass = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
Wukong = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
`Grass + Wukong` = c(1,0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA)
del_errors = data.frame(sub_perc, DNA_Aeon, Hedges, Derrick, Grass, Wukong, `Grass + Wukong`,`DNA-Aeon + Derrick`)

```

```{r, echo=FALSE}

colors = c('DNA-Aeon + Derrick' = 'blue', 'Hedges' = 'darkorange3', 'Grass + Wukong' = 'darkgreen')
ggplot(del_errors, aes(sub_perc)) +
  geom_line(aes(y = `DNA-Aeon + Derrick`, color = 'DNA-Aeon + Derrick'), size = 1) +
  geom_line(aes(y = Hedges, color = 'Hedges'), size = 1) +
  geom_line(aes(y = `Grass + Wukong`, color = 'Grass + Wukong'), size = 1) +
  #geom_line(aes(y = Derrick, color = 'Derrick'), size = 1) +
  #geom_line(aes(y = Wukong, color = 'Wukong'), size = 1) +
  geom_point(aes(y = `DNA-Aeon + Derrick`), color = 'blue', size = 2) +
  geom_point(aes(y = Hedges), color = 'darkorange3', size = 2) +
  geom_point(aes(y = `Grass + Wukong`), color = 'darkgreen', size = 2) +
  #geom_point(aes(y = Derrick), color = 'brown', size = 2) +
  #geom_point(aes(y = Wukong), color = 'darkorchid', size = 2) +
  xlab('Error Rate') +
  ylab('Proportion Recovered') +
  ggtitle('% Recovered VS Deletion Error Rate') +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position=c(.85,.75),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"),
        text=element_text(size=13)) +
  scale_color_manual(name = 'Encoding Method',
                     breaks = c('DNA-Aeon + Derrick','Hedges', 'Grass + Wukong'),
                     values = c('DNA-Aeon + Derrick' = 'blue', 'Hedges' = 'darkorange3',
                                'Grass + Wukong' = 'darkgreen' )) +
  scale_x_continuous("Error Rate", limits = c(0,0.08), breaks = seq(0.00,0.1, length = 11))

ggsave('Del_recover.png', width= 10, height = 5)
```

Analysis of composition

```{r}
gc_content = seq(0.46,0.59, length = 14)
gc_count = c(2,1,7,8,22,39,34,41,43,19,13,14,7,5)
gc_hedges = data.frame(gc_content, gc_count)

gc_content = seq(0.41, 0.56, length = 16)
gc_count = c(1,1,0,3,32,46,78,137,138,151,140,108,75,43,42,5)
gc_aeon = data.frame(gc_content, gc_count)

gc_content = seq(0.41, 0.59, length = 19) #Artificially split up
gc_count = c(3,6,9,7,17,20,59,46,44,27,51,29,37,29,16,11,4,1,1)
gc_grass = data.frame(gc_content, gc_count)

gc_content = seq(0.44,0.57, length = 14)
gc_count = c(2,1,7,22,31,52,30,40,28,14,13,10,4,1)
gc_derrick = data.frame(gc_content, gc_count)

gc_content = seq(0.46, 0.60, length = 15)
gc_count = c(3,3,6,8,14,25,43,56,67,82,124,67,36,24,2)
gc_wukong = data.frame(gc_content, gc_count)
```

```{r}
ggplot(gc_wukong, aes(x = gc_content, y = gc_count)) +
  geom_bar(stat = "identity", color = 'black', fill = 'cyan3') +
  ggtitle('GC Distribution Wukong') +
  theme_bw() +
  ylab('Counts') +
  xlab('GC Content') +
  theme(plot.title = element_text(hjust = 0.5),
        text=element_text(size=13)) +
  xlim(0.4, 0.65) +
  scale_x_continuous(limits = c(0.4,0.65), 
                     breaks = c(0.4,0.42,0.44,0.46,0.48,0.50,0.52,0.54,0.56,0.58,0.60,0.62,0.64))

ggsave('GC_Wukong.png', width= 10, height = 6)
```


```{r}
#Polymers

polsizes = c(3,4,5,6)
pol_aeon = c(11250/110000,NA,NA,NA)
pol_hedges = c(6114/76500,1952/76500, NA, NA)
pol_grass = c(5289/83421,NA,NA,NA)
pol_derrick = c(10323/102000, 3636/102000, 1120/102000, 372/102000)
pol_wukon = c(13791/112000, 5016/112000, NA,NA)

polaeon = data.frame(polsizes,pol_aeon)
polhedges = data.frame(polsizes,pol_hedges)
polgrass = data.frame(polsizes, pol_grass)
polderrick = data.frame(polsizes, pol_derrick)
polwukon = data.frame(polsizes, pol_wukon)
```

```{r}
polaeon['Encoder'] = 'DNA-Aeon'
polhedges['Encoder'] = 'Hedges'
polgrass['Encoder'] = 'Grass'
polderrick['Encoder'] = 'Derrick'
polwukon['Encoder'] = 'Wukong'
colnames(polaeon) = c('Polymer Sizes', 'Proportion', 'Encoder')
colnames(polhedges) = c('Polymer Sizes', 'Proportion', 'Encoder')
colnames(polgrass) = c('Polymer Sizes', 'Proportion', 'Encoder')
colnames(polderrick) = c('Polymer Sizes', 'Proportion', 'Encoder')
colnames(polwukon) = c('Polymer Sizes', 'Proportion', 'Encoder')
polall = rbind(polaeon, polhedges)
polall = rbind(polall, polgrass)
polall = rbind(polall, polderrick)
polall = rbind(polall, polwukon)
```

```{r, echo = False}
#Polymer plotting
ggplot(polall, aes(x = `Polymer Sizes`, y=Proportion, fill = Encoder)) +
  geom_bar(stat = "identity", position = 'dodge', color = 'black', width = 0.6) +
  ggtitle('Homopolymer Proportions') +
  theme_bw() +
  ylab('Proportion') +
  xlab('Homopolymer Size') +
  theme(plot.title = element_text(hjust = 0.5),
        text=element_text(size=13)) +
  scale_x_continuous(breaks = c(3,4,5,6), limits = c(2.5,6.5)) +
  ylim(0,0.125)

ggsave('Homopolymer_Proportions.png', width= 10, height = 6)
```

```{r}
#Dimers
#Trimers

disizes = c(2,3,4,5)
di_aeon = c(8756/110000, 756/110000, 80/110000, NA)
tri_aeon = c(2988/110000, 90/110000, NA, NA)
di_hedges = c(6748/76500, 372/76500, 48/76500, 10/76500)
tri_hedges = c(1884/76500, 27/76500, NA, NA)
di_grass = c(9016/83421, 1194/83421, 112/83421,10/83421)
tri_grass = c(3168/83421, 45/83421, NA, NA)
di_derrick = c(11356/102000, 1014/102000, 48/102000, NA)
tri_derrick = c(2826/102000, 81/102000, NA, NA)
di_wukong = c(9972/112000,708/112000, 32/112000, NA)
tri_wukong = c(3798/112000, 63/112000, NA, NA)
```

```{r}
diaeon = data.frame(disizes, di_aeon)
dihedges = data.frame(disizes, di_hedges)
digrass = data.frame(disizes, di_grass)
diderrick = data.frame(disizes, di_derrick)
diwukong = data.frame(disizes, di_wukong)
diaeon['Encoder'] = 'DNA-Aeon'
dihedges['Encoder'] = 'Hedges'
digrass['Encoder'] = 'Grass'
diderrick['Encoder'] = 'Derrick'
diwukong['Encoder'] = 'Wukong'
colnames(diaeon) = c('Dimer Size','Proportion', 'Encoder')
colnames(dihedges) = c('Dimer Size','Proportion', 'Encoder')
colnames(digrass) = c('Dimer Size','Proportion', 'Encoder')
colnames(diderrick) = c('Dimer Size','Proportion', 'Encoder')
colnames(diwukong) = c('Dimer Size','Proportion', 'Encoder')

diall = rbind(diaeon, dihedges)
diall = rbind(diall, digrass)
diall = rbind(diall, diderrick)
diall = rbind(diall, diwukong)
```

```{r}
triaeon = data.frame(disizes, tri_aeon)
trihedges = data.frame(disizes, tri_hedges)
trigrass = data.frame(disizes, tri_grass)
triderrick = data.frame(disizes, tri_derrick)
triwukong = data.frame(disizes, tri_wukong)
triaeon['Encoder'] = 'DNA-Aeon'
trihedges['Encoder'] = 'Hedges'
trigrass['Encoder'] = 'Grass'
triderrick['Encoder'] = 'Derrick'
triwukong['Encoder'] = 'Wukong'
colnames(triaeon) = c('Dimer Size','Proportion', 'Encoder')
colnames(trihedges) = c('Dimer Size','Proportion', 'Encoder')
colnames(trigrass) = c('Dimer Size','Proportion', 'Encoder')
colnames(triderrick) = c('Dimer Size','Proportion', 'Encoder')
colnames(triwukong) = c('Dimer Size','Proportion', 'Encoder')

triall = rbind(triaeon, trihedges)
triall = rbind(triall, trigrass)
triall = rbind(triall, triderrick)
triall = rbind(triall, triwukong)
```

```{r}
#Plotting dimers/trimers
ggplot(triall, aes(x = `Dimer Size`, y = Proportion, fill = Encoder)) +
  geom_bar(stat = "identity", position = 'dodge', color = 'black', width = 0.6) +
  ggtitle('Proportion of Bases in Trimers') +
  theme_bw() +
  ylab('Proportion') +
  xlab('No. of Repeating Elements') +
  theme(plot.title = element_text(hjust = 0.5),
        text=element_text(size=13)) +
  scale_x_continuous(breaks = c(2,3,4,5), limits = c(1.5,5.5)) +
  ylim(0,0.05)
ggsave('Trimer_Proportions.png', width= 10, height = 6)
```

